<?php

namespace App\Domain\Scoring;

use App\Domain\Consequences\KpiConsequenceReferencePackage;
use App\Enums\KpiDefinitionStatus;
use App\Models\KpiDefinition;
use Brick\Math\BigDecimal;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

final class KpiDefinitionCatalog
{
    public const HALDEN_KPI_VERSION = 'halden_kpi_consequence_v1_0_1';

    public function __construct(
        private readonly KpiConsequenceReferencePackage $package,
    ) {}

    /**
     * @return list<array<string, mixed>>
     */
    public function haldenSevenKpis(): array
    {
        $names = [
            'integrated_margin_per_boe' => ['Integrated margin per BOE', 'Integrated economics per BOE from the package-backed financial state.'],
            'roace' => ['ROACE', 'Return on average capital employed from the package-backed financial state.'],
            'free_cash_flow' => ['Free cash flow', 'Free cash flow generated by the package-backed financial state.'],
            'refining_net_margin_vs_benchmark' => ['Refining net margin vs benchmark', 'Refining margin compared with the benchmark basis.'],
            'retail_non_fuel_margin_per_site' => ['Retail non-fuel margin per site', 'Retail non-fuel margin on a per-site basis.'],
            'net_debt_to_ebitda' => ['Net debt to EBITDA', 'Net leverage relative to EBITDA.'],
            'asset_health_index' => ['Asset health index', 'Composite asset health state.'],
        ];

        return array_map(function (array $row) use ($names): array {
            $key = $row['key'];
            [$name, $description] = $names[$key] ?? [str($key)->replace('_', ' ')->title()->toString(), 'Package-backed KPI definition.'];

            return [
                'key' => $key,
                'name' => $name,
                'description' => $description,
                'weight' => (string) BigDecimal::of($row['weight'])->toScale(6),
                'calculation_source' => $row['formula'],
                'direction' => $row['direction'],
            ];
        }, $this->package->kpiDefinitions());
    }

    /**
     * @return Collection<int, KpiDefinition>
     */
    public function publishHaldenV1(): Collection
    {
        $definitions = $this->haldenSevenKpis();
        $this->assertWeightsSumToOne($definitions);

        return DB::transaction(function () use ($definitions): Collection {
            $models = collect();

            foreach ($definitions as $definition) {
                $models->push(KpiDefinition::query()->firstOrCreate(
                    [
                        'key' => $definition['key'],
                        'version' => self::HALDEN_KPI_VERSION,
                    ],
                    [
                        'name' => $definition['name'],
                        'description' => $definition['description'],
                        'weight' => $definition['weight'],
                        'calculation_source' => $definition['calculation_source'],
                        'status' => KpiDefinitionStatus::Published->value,
                        'effective_from' => now()->toDateString(),
                        'metadata' => [
                            'source' => KpiConsequenceReferencePackage::PACKAGE_ROOT,
                            'package_version' => $this->package->version(),
                            'direction' => $definition['direction'] ?? 'higher',
                            'source_hashes' => $this->package->sourceHashes(),
                        ],
                    ],
                ));
            }

            return $models;
        });
    }

    /**
     * @param  iterable<array<string, mixed>|KpiDefinition>  $definitions
     */
    public function assertWeightsSumToOne(iterable $definitions): void
    {
        $sum = BigDecimal::zero();

        foreach ($definitions as $definition) {
            $weight = $definition instanceof KpiDefinition ? $definition->weight : $definition['weight'];
            $sum = $sum->plus((string) $weight);
        }

        if (! $sum->isEqualTo('1.000000')) {
            throw new InvalidArgumentException("Published KPI weights must sum to 1.000000; received {$sum}.");
        }
    }
}
