<?php

namespace App\Domain\Scoring;

use App\Enums\KpiDefinitionStatus;
use App\Models\KpiDefinition;
use Brick\Math\BigDecimal;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use InvalidArgumentException;

final class KpiDefinitionCatalog
{
    public const HALDEN_KPI_VERSION = 'halden_kpi_v1';

    /**
     * @return list<array<string, mixed>>
     */
    public function haldenSevenKpis(): array
    {
        return [
            [
                'key' => 'integrated_margin_per_boe',
                'name' => 'Integrated margin per BOE',
                'description' => 'Integrated economics per BOE from supported deterministic resolution outputs.',
                'weight' => '0.300000',
                'calculation_source' => 'economic_resolution.integrated_margin_per_boe',
            ],
            [
                'key' => 'roace',
                'name' => 'ROACE',
                'description' => 'Return on average capital employed.',
                'weight' => '0.150000',
                'calculation_source' => 'standing.roace',
            ],
            [
                'key' => 'free_cash_flow',
                'name' => 'Free cash flow',
                'description' => 'Free cash flow generated by team decisions.',
                'weight' => '0.150000',
                'calculation_source' => 'cash_flow.free_cash_flow',
            ],
            [
                'key' => 'refining_net_margin_vs_benchmark',
                'name' => 'Refining net margin vs benchmark',
                'description' => 'Refining margin compared with the benchmark basis.',
                'weight' => '0.100000',
                'calculation_source' => 'economic_resolution.refining_net_margin_vs_benchmark',
            ],
            [
                'key' => 'retail_non_fuel_margin_per_site',
                'name' => 'Retail non-fuel margin per site',
                'description' => 'Retail non-fuel margin on a per-site basis.',
                'weight' => '0.100000',
                'calculation_source' => 'retail.non_fuel_margin_per_site',
            ],
            [
                'key' => 'net_debt_to_ebitda',
                'name' => 'Net debt to EBITDA',
                'description' => 'Net leverage relative to EBITDA.',
                'weight' => '0.100000',
                'calculation_source' => 'debt.net_debt_to_ebitda',
            ],
            [
                'key' => 'asset_health_index',
                'name' => 'Asset health index',
                'description' => 'Composite asset health state.',
                'weight' => '0.100000',
                'calculation_source' => 'asset_health.index',
            ],
        ];
    }

    /**
     * @return Collection<int, KpiDefinition>
     */
    public function publishHaldenV1(): Collection
    {
        $definitions = $this->haldenSevenKpis();
        $this->assertWeightsSumToOne($definitions);

        return DB::transaction(function () use ($definitions): Collection {
            $models = collect();

            foreach ($definitions as $definition) {
                $models->push(KpiDefinition::query()->firstOrCreate(
                    [
                        'key' => $definition['key'],
                        'version' => self::HALDEN_KPI_VERSION,
                    ],
                    [
                        'name' => $definition['name'],
                        'description' => $definition['description'],
                        'weight' => $definition['weight'],
                        'calculation_source' => $definition['calculation_source'],
                        'status' => KpiDefinitionStatus::Published->value,
                        'effective_from' => now()->toDateString(),
                        'metadata' => ['source' => 'Batch 5A Halden KPI framework'],
                    ],
                ));
            }

            return $models;
        });
    }

    /**
     * @param  iterable<array<string, mixed>|KpiDefinition>  $definitions
     */
    public function assertWeightsSumToOne(iterable $definitions): void
    {
        $sum = BigDecimal::zero();

        foreach ($definitions as $definition) {
            $weight = $definition instanceof KpiDefinition ? $definition->weight : $definition['weight'];
            $sum = $sum->plus((string) $weight);
        }

        if (! $sum->isEqualTo('1.000000')) {
            throw new InvalidArgumentException("Published KPI weights must sum to 1.000000; received {$sum}.");
        }
    }
}
